version: 0.2

phases:
  install:
    commands:
      - sudo pip install --upgrade awscli  
  build:
    commands:
      - echo Build started on 'date'
  post_build:
    commands:
      - echo Build completed on 'date'
      - mvn package
      - aws cloudformation package --template-file ./src/main/resources/template/APITemplate.json --s3-bucket artifact-demo-2
                                   --output-template-file APITemplate.json
artifacts:
  type: zip
  files:
    - APITemplate.json
    - target/cards-0.0.1-SNAPSHOT-jar-with-dependencies.jar
