version: 0.2

phases:
  build:
    commands:
      - echo Build started on 'date'
      - mvn test
  post_build:
    commands:
      - echo Build completed on 'date'
      - mvn package
artifacts:
  type: zip
  files:
    - target/cards-0.0.1-SNAPSHOT.jar
    - ./src/main/resources/template/APITemplate.json